### PR TITLE
Fix: otp extra & doSendPassword

### PR DESCRIPTION
**Pull request by lukasmatusiewicz**
+ Implement the authentication flows.
+ Update the authsource config template with an `authenticationFlow` option. Valid values are: `sendPass`, `triggerChallenge`, and `otpExtra`.
+ `doTriggerChallenge`, `doSendPassword` and `otpExtra` options are outdated and removed from the config template.
+  `authenticationFlow` is required. If the option isn't found or the value is invalid, the login mask contains per default: 1 username field and 1 pass field, and a proper error is written to the log.
+ Implement the `authenticationFlow` in `authproc`. Valid values: `default`, `triggerChallenge`.
+ rm submodule configuration and belonging files from the repo.
+ Fix: process token enrollment after trigger challenge if is set.

### CODE REVIEW

**Review by nilsbehlen — CHANGES_REQUESTED** [review]
We should do some more thinking about the names.
`authSourceMode` is too specific for ssp, we should pick a name that we can use in other plugins too. I was thinking something like `AuthenticationFlow`, using the word `flow` to distinguish from the `mode`/`client_mode` that the plugin has internally that corresponds to the current token type used for authentication.
I also do not like `otpExtra` and would vouch for something like `otpSeparate` because it is more precise for what it does.

If we implement the authSourceMode/AuthenticationFlow setting, we should also think about how we control the UI elements so it is as easy as possible to introduce new modes/flows, as well as `client_modes`.

**Comment by lukasmatusiewicz** [comment]
I like your idea to use the term: `AuthenticationFlow`.

And as an alternative for `otpExtra`, to concern can also be:
- splitPassFields
- furtherPassField
- separateOTP
- detachedOTP.

**Comment by lukasmatusiewicz** [comment]
- [ ] Add authentication flow to `authproc`

**Comment by lukasmatusiewicz** [comment]
1. The logic in authproc differs from authsource. Default option is just to not process any of the other flows. Normally this is not bad, authFlow is required even if it isn't.
Maybe we should call it here: changeFlow or undefaultFlow?

**Comment by nilsbehlen** [comment]
We should add more context to the documentation `privacyidea.md` for the AuthSource settings `detailmap`. What does it do?
Are those the attributes that will be returned to SAML?
Also add a short description of the policy that has to be set in privacyidea to have the SAML attributes returned from validate check. I've marked the spot in the "User Attributes" section.

**Review by nilsbehlen — APPROVED** [review]

**Pull request merged**
