### PR TITLE
Update `.gitignore`

### PR DESCRIPTION
**Pull request by NuvandaPV**

### CODE REVIEW

**Comment by NuvandaPV** [comment]
fixes #69

**Comment by Mipronimo** [comment]
Is this necessary? We have the `default-enable`, so you do not have to add `enable` manually, which means, that this does not have to be ignored :smile:

What do you think?

**Comment by NuvandaPV** [comment]
Oh, I didn't even realize that, thanks for pointing it out :see_no_evil: Should we remove the instructions asking the user to create this file from README.md then?

**Comment by Mipronimo** [comment]
Oh yeah.. That would make sense 😄

**Pull request closed without merging**
