### PR TITLE
Fixed passHint in pi-form.twig

### PR DESCRIPTION
**Pull request by enricomv**
Tis fix the issue #214 https://github.com/privacyidea/simplesamlphp-module-privacyidea/issues/214

### CODE REVIEW

**Review by lukasmatusiewicz — APPROVED** [review]

**Comment by enricomv** [comment]
Dear @lukasmatusiewicz, sorry for my naive contribution, but I forgot to update the version number. Can you please update it and tag in order to be available to composer? Thank you in advance.

**Comment by lukasmatusiewicz** [comment]
Yeah, no problemo

**Comment by enricomv** [comment]
> Yeah, no problemo

Sorry, but the tag and version is still 4.0.0 
There is any thing I have to do?

**Comment by lukasmatusiewicz** [comment]
Sorry, added a tag but forgot to release. Now it should work.
Thank you:)

**Pull request merged**
