### PR TITLE
Skip other sites if the user has already completed 2FA

### PR DESCRIPTION
**Pull request by kcolwell**
Hi,

I couldn't figure out a way to stop privacyidea from doing 2FA when using the authproc method or "Method 2" when you are going between different sites. So, you login to site one, then do the 2FA, and then visit site two and it asks you to do the 2FA again.

Since, I couldn't figure out a way to do this, feel free to correct me if I'm wrong about this, I created a configuration option and some code.

### CODE REVIEW

**Comment by laclaro** [comment]
I like the enhancement. But please think about the name of the option. What are "other related sites"? Please specify.

**Comment by spaceone** [comment]
This could also be solved simpler with #91 by ignoring the auth proc filter when `SimpleSAML_Session::getSessionFromRequest()->getData('privacyidea:privacyidea', 'authenticated')`. (aka moving this check out of the `if($state['isPassive'] === true)` block).

**Comment by cornelinux** [comment]
@kcolwell thanks for your request. We are about the solve this in another PR, so we will close this PR shortly.

**Comment by spaceone** [comment]
This issue was mentioned here: https://groups.google.com/g/simplesamlphp/c/iaJICHisvyc/m/7p_90aogAQAJ

**Comment by laclaro** [comment]
closed by #106

**Pull request closed without merging**
