### PR TITLE
Multiple enhancements regarding correct encoding

### PR DESCRIPTION
**Pull request by spaceone**
Fix some encoding errors to strengthen security.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/privacyidea/simplesamlphp-module-privacyidea/pull/10%23issuecomment-259537461%22%2C%20%22https%3A//github.com/privacyidea/simplesamlphp-module-privacyidea/pull/10%23issuecomment-259952001%22%2C%20%22https%3A//github.com/privacyidea/simplesamlphp-module-privacyidea/pull/10%23issuecomment-269663807%22%2C%20%22https%3A//github.com/privacyidea/simplesamlphp-module-privacyidea/pull/10%23issuecomment-274085404%22%2C%20%22https%3A//github.com/privacyidea/simplesamlphp-module-privacyidea/pull/10%23issuecomment-274195344%22%2C%20%22https%3A//github.com/privacyidea/simplesamlphp-module-privacyidea/pull/10%23issuecomment-274246827%22%2C%20%22https%3A//github.com/privacyidea/simplesamlphp-module-privacyidea/pull/10%23issuecomment-274247641%22%2C%20%22https%3A//github.com/privacyidea/simplesamlphp-module-privacyidea/pull/10%23issuecomment-274248499%22%2C%20%22https%3A//github.com/privacyidea/simplesamlphp-module-privacyidea/pull/10%23issuecomment-274249907%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/privacyidea/simplesamlphp-module-privacyidea/pull/10%23issuecomment-259537461%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Urgs%5Cu2026%20your%20commit%20cam%20between%3A%5Cr%5Cnhttps%3A//github.com/privacyidea/simplesamlphp-module-privacyidea/commit/c9448f7673c1f0017a08e42a10e685f46c516d14%5Cr%5Cn%5Cr%5CnI%20don%27t%20want%20to%20rebase%20%3AD%22%2C%20%22created_at%22%3A%20%222016-11-09T21%3A54%3A25Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1100188%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/spaceone%22%7D%7D%2C%20%7B%22body%22%3A%20%22I%20am%20working%20also%20on%20some%20theme%20stuff.%20When%20I%20am%20done%2C%20I%20will%20take%20a%20look%20at%20your%20PR%2C%20%5Cr%5CnThanks%20a%20lot%21%22%2C%20%22created_at%22%3A%20%222016-11-11T12%3A58%3A12Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1908620%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/cornelinux%22%7D%7D%2C%20%7B%22body%22%3A%20%22The%20plugin%20had%20some%20major%20rewrites.%20Would%20it%20be%20ok%20for%20you%2C%20to%20recheck%20it%20and%20resubmit%20a%20PR%3F%5Cr%5Cn%5Cr%5CnBy%20the%20way%3A%20Happy%20new%20year.%20%3A-%29%22%2C%20%22created_at%22%3A%20%222016-12-29T17%3A29%3A29Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1908620%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/cornelinux%22%7D%7D%2C%20%7B%22body%22%3A%20%22Happy%20new%20year.%20Yes%2C%20I%20will%20have%20a%20look%20at%20this%20in%20the%20next%20weeks%20%3A%29%22%2C%20%22created_at%22%3A%20%222017-01-20T14%3A31%3A30Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1100188%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/spaceone%22%7D%7D%2C%20%7B%22body%22%3A%20%22I%20rebased%20the%20changes%2C%20you%20can%20merge%20them%20in%20now%20%3A%29%22%2C%20%22created_at%22%3A%20%222017-01-20T22%3A19%3A53Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1100188%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/spaceone%22%7D%7D%2C%20%7B%22body%22%3A%20%22What%20editor%20are%20you%20using%20so%20that%20you%20are%20changing%20all%20indentations%3F%5Cr%5CnIs%20it%20a%20php%20requirement%20to%20have%208%20instead%20of%204%3F%22%2C%20%22created_at%22%3A%20%222017-01-21T07%3A49%3A15Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1908620%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/cornelinux%22%7D%7D%2C%20%7B%22body%22%3A%20%22Well%2C%20the%20files%20were%20tab%20indented%20some%20weeks%20ago%20and%20there%20were%20some%20lines%20with%20spaces%20so%20i%20changed%20this.%20if%20you%20want%20i%20can%20change%20this%20back%20to%20spaces%20in%20a%20extra%20commit%20%28i%20don%27t%20want%20to%20rebase%20with%20whitespace%20changes%29.%20I%20am%20using%20vim%20which%20displays%20tabs%20as%204%20spaces.%20the%20github%20webinterface%20displays%20them%20as%208%20spaces.%22%2C%20%22created_at%22%3A%20%222017-01-21T08%3A09%3A34Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1100188%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/spaceone%22%7D%7D%2C%20%7B%22body%22%3A%20%22OK%2C%20I%20think%20I%20just%20take%20you%20PR%20an%20run%20my%20phpstorm%20over%20it.%20Thanks%21%22%2C%20%22created_at%22%3A%20%222017-01-21T08%3A33%3A00Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1908620%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/cornelinux%22%7D%7D%2C%20%7B%22body%22%3A%20%22Ah%20ok.%20I%20understand.%20You%20changed%20everything%20to%20tabs.%20I%20think%20it%20is%20more%20consistent%20to%20have%20spaces%2C%20which%20in%20fact%20is%20also%20recommended.%20I%20will%20change%20this%20to%204%20spaces...%22%2C%20%22created_at%22%3A%20%222017-01-21T09%3A11%3A10Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1908620%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/cornelinux%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/privacyidea/simplesamlphp-module-privacyidea/pull/10#issuecomment-259537461'>General Comment</a></b>
- <a href='https://github.com/spaceone'></a> Urgs… your commit cam between:
https://github.com/privacyidea/simplesamlphp-module-privacyidea/commit/c9448f7673c1f0017a08e42a10e685f46c516d14
I don't want to rebase :D
- <a href='https://github.com/cornelinux'></a> I am working also on some theme stuff. When I am done, I will take a look at your PR,
Thanks a lot!
- <a href='https://github.com/cornelinux'></a> The plugin had some major rewrites. Would it be ok for you, to recheck it and resubmit a PR?
By the way: Happy new year. :-)
- <a href='https://github.com/spaceone'></a> Happy new year. Yes, I will have a look at this in the next weeks :)
- <a href='https://github.com/spaceone'></a> I rebased the changes, you can merge them in now :)
- <a href='https://github.com/cornelinux'></a> What editor are you using so that you are changing all indentations?
Is it a php requirement to have 8 instead of 4?
- <a href='https://github.com/spaceone'></a> Well, the files were tab indented some weeks ago and there were some lines with spaces so i changed this. if you want i can change this back to spaces in a extra commit (i don't want to rebase with whitespace changes). I am using vim which displays tabs as 4 spaces. the github webinterface displays them as 8 spaces.
- <a href='https://github.com/cornelinux'></a> OK, I think I just take you PR an run my phpstorm over it. Thanks!
- <a href='https://github.com/cornelinux'></a> Ah ok. I understand. You changed everything to tabs. I think it is more consistent to have spaces, which in fact is also recommended. I will change this to 4 spaces...

<a href='https://www.codereviewhub.com/privacyidea/simplesamlphp-module-privacyidea/pull/10?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/privacyidea/simplesamlphp-module-privacyidea/pull/10?approve=1'></a>&nbsp;<a href='https://github.com/privacyidea/simplesamlphp-module-privacyidea/pull/10'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by cornelinux** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/privacyidea/simplesamlphp-module-privacyidea/pull/10'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by spaceone** [comment]
Urgs… your commit cam between:
https://github.com/privacyidea/simplesamlphp-module-privacyidea/commit/c9448f7673c1f0017a08e42a10e685f46c516d14

I don't want to rebase :D

**Comment by cornelinux** [comment]
I am working also on some theme stuff. When I am done, I will take a look at your PR, 
Thanks a lot!

**Comment by cornelinux** [comment]
The plugin had some major rewrites. Would it be ok for you, to recheck it and resubmit a PR?

By the way: Happy new year. :-)

**Comment by spaceone** [comment]
Happy new year. Yes, I will have a look at this in the next weeks :)

**Comment by spaceone** [comment]
I rebased the changes, you can merge them in now :)

**Comment by cornelinux** [comment]
What editor are you using so that you are changing all indentations?
Is it a php requirement to have 8 instead of 4?

**Comment by spaceone** [comment]
Well, the files were tab indented some weeks ago and there were some lines with spaces so i changed this. if you want i can change this back to spaces in a extra commit (i don't want to rebase with whitespace changes). I am using vim which displays tabs as 4 spaces. the github webinterface displays them as 8 spaces.

**Comment by cornelinux** [comment]
OK, I think I just take you PR an run my phpstorm over it. Thanks!

**Comment by cornelinux** [comment]
Ah ok. I understand. You changed everything to tabs. I think it is more consistent to have spaces, which in fact is also recommended. I will change this to 4 spaces...

**Pull request merged**
