### PR TITLE
Labels fix

### PR DESCRIPTION
**Pull request by melanger**
- add content to labels
- use labels for form fields only

Label text is accessible only to screen readers, so the visual part should be unchanged.

To be merged after https://github.com/privacyidea/simplesamlphp-module-privacyidea/pull/121

### CODE REVIEW

**Comment by lukasmatusiewicz** [comment]
Hi @melanger,

we have a conflict, because I had to leave inline CSS as it was. Because extern CSS files are not working with UCS (and maybe other services too). We have to prove it. Have you any idea how to fix it btw?

Can you do a new pull request for that label changes to the new master state?

Thank you!

**Comment by melanger** [comment]
What is the problem with external CSS? It should work the same way you have external JavaScript in there...

I will be glad to help with "fixing" the external CSS, but I don't want to go with inline CSS, I want a strict Content Security Policy to minimize security risks.

**Comment by melanger** [comment]
I can think of a possible problem - if the external CSS is not being applied with a different SimpleSAMLphp template, it might be because inline CSS has precedence over any external CSS, but with two external CSS files, the precedence is determined by how much the CSS selector is specific, then by order of files and order in the file. So, if you need to override some CSS of a template, you can make the CSS selectors more specific and/or include the stylesheet later in the HTML and/or add `!important` to these CSS rules.

**Comment by lukasmatusiewicz** [comment]
Thank you for your co-work. Yes, extern js works well. But CSS for some reason not. I have tried with !important in every line of your CSS. But that doesn't help. I have read about themes in simplesamlphp and there is one way to do this by building our own theme, but we can't ask all of the users to add our theme in config just to adjust the buttons. And if they will use another theme it will be messed again.

**Comment by melanger** [comment]
I would hate to create a hard fork of this module, but the inline styles and #28 are tempting me to do so. I hope it won't come to that.

**Comment by lukasmatusiewicz** [comment]
Hi, thank you very much. Yes, it is Univention Corporate Server 5.0. They have their own theme which our plugin is using. You can download our privacyidea-simplesaml plugin in appstore there. Thank you one more time!

**Comment by lukasmatusiewicz** [comment]
Hi @melanger,

I have checked what possibilities we have to separate the CSS and I found the solution. If it will work well we will publish it with the next version which comes soon.

Thank you for your support and contribution!

**Pull request merged**
